version: '3.8'

services:
  grpc-server:
    build:
      context: .
      dockerfile: docker/grpc.Dockerfile
    networks:
      grpc_net:
        aliases:
          - grpc-servers
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - SERVER_ID={{.Task.Slot}}

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "50051:50051"
    networks:
      - grpc_net
    depends_on:
      - grpc-server

  http-server:
    build:
      context: .
      dockerfile: docker/http.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - grpc_net
    depends_on:
      - nginx

networks:
  grpc_net:
    driver: bridge
